- bucket/icaros-np.json
Since v3.3.0 beta 1 the way filetypes are stored in the registry has changed.
From the [release notes](https://shark007.net/forum/Thread-New-Release-3-3-0-Beta-1):
>With this release I've changed the way Icaros' property settings are stored in the registry.
Some new features required Icaros to be able to detect what properties was available in a users
previously installed build, and that wasn't possible with the current setup.
>...
>Icaros will automatically generate this list if it does not already exist, during registration/unregistration.
The list is generated with default values for each filetype.
Therefore it's no longer necessary to set the default filetype registry key manually as it will be created automatically.
> icaros-np: remove registry modification

- bucket/peace-np.json
When I last installed Peace via scoop there was an error due to the desktop shortcut not existing when it tried to remove it. The installation still completed successfully though the desktop shortcut was not created until after launching Peace.
So this simply checks if the shortcut is there before removing it.
> peace-np: check for shortcut before removal

- bucket/winbtrfs-np.json
Suggestion from https://github.com/ScoopInstaller/Nonportable/pull/22#issuecomment-1179668711
> winbtrfs-np: Use break instead of exit

- bucket/winfsp-np.json
As far as I know there is no easy related to this PR, aside from this PR itself.
While attempting to use winfsp-np I noticed that it did not include the header files and developer libraries in the default install. After a bit of exploration my part(recently started using Windows after 15+ years away) I figured out installer flags to add to make it install the Developer feature set. There are some other features, but I didn't want to enable them as they seemed to have more far reaching impact than just the addition of developer files.
> winfsp-np: Enable Developer option so that headers and libraries are installed

- bucket/iddsampledriver-ge9-np.json
When updating, a duplicate device will appear in the device manager, so it is best to uninstall the existing driver first before installing the new one when upgrading.
> iddsampledriver-ge9-np: Remove uninstall check on uninstaller

- bucket/winbtrfs-np.json
- scripts/winbtrfs-np/no-reboot.ahk
Use nefcon to install the driver without using an AutoHotkey script and properly uninstall the driver service on uninstallation.
> winbtrfs-np: Use nefcon to properly install and uninstall the driver

- bucket/spotx-np.json
Hi
You can tweak the script so that after installation the shortcut is not deleted from the desktop, since it is not very convenient for users to look for it elsewhere.
> spotx: Do not delete Spotify desktop shortcut

- bucket/zerotier-np.json
The hash of the original download address changes frequently, causing frequent download or update failures.
Local test passed.
> zerotier-np: Better address for automatic updates

- bucket/lavfilters-np.json
LAV Filters are a set of DirectShow filters based on the libavformat and libavcodec libraries
from the ffmpeg project, which will allow you to play virtually any format in a DirectShow player.
https://github.com/Nevcairiel/LAVFilters
---
> lavfilters-np: Add version 0.76.1

- bucket/anki-np.json
Fixes Anki autoupdate which was broken since they implemented alternative versions for Qt versions, and updates it to the latest version.
> anki-np: Fix autoupdate

- bucket/stevedore-np.json
Adds [stevedore](https://github.com/slonopotamus/stevedore) to the bucket.
Pretty much a straight, updated copy of TheRandomLabs/scoop-nonportable#296 (done with the original author's permission).
> stevedore-np: Add version 0.8.0

- bucket/virtualbox-np.json
Fixes "Can't shim 'VBoxSDL.exe': File doesn't exist." when trying to install current version of virtualbox-np.json
> virtualbox-np: Remove VBoxSDL.exe

- bucket/virtualbox-with-extension-pack-np.json
Fixes "Can't shim 'VBoxSDL.exe': File doesn't exist." when trying to install current version of virtualbox-with-extension-pack-np.json
> virtualbox-with-extension-pack-np@7.0.0: Remove VBoxSDL.exe

- bucket/spotx-np.json
https://github.com/SpotX-CLI/SpotX-Win/issues/54
Since the repository link changed, it caused an incorrect version error.
Please check if everything is ok now
> SpotX-np: Changing the repository link

- bucket/mactype-np.json
- Changed `checkver` to get the proper tag from the github api
- Reverted the manifest to 2021.1-rc1
Closes #82
> mactype-np: Fix checkver and update to 2021.1-rc1

- bucket/teracopy-np.json
Fixes test failures in my other PR https://github.com/ScoopInstaller/Nonportable/actions/runs/3536293824/jobs/5935195181#step:4:29
```
Error: [-] any leading whitespace consists only of spaces (excepting makefiles) 39ms (37ms|2ms)
Message
RuntimeException: The following 2 lines contain TABs within leading whitespace: 
File: D:\a\Nonportable\Nonportable\my_bucket\bucket\teracopy-np.json, Line: 11
File: D:\a\Nonportable\Nonportable\my_bucket\bucket\teracopy-np.json, Line: 12
at <ScriptBlock>, D:\a\Nonportable\Nonportable\scoop_core\test\Scoop-00File.Tests.ps1:185
```
Relates to #99
> teracopy-np: Fix tests

- bucket/lav-filters-megamix-np.json
Removed extra quotes on the `$dir` variable so it doesn't break the installer
Closes #63
> lav-filters-megamix-np: Fix installer

- bucket/spotx-np.json
The manifest has been updated by the excavator recently with wrong version numbers as seen here https://github.com/ScoopInstaller/Nonportable/commits/master/bucket/spotx-np.json
I made a few changes to the script in an attempt to prevent this:
- switched the second url to use the api as well
- better error handling
> spotx-np: Fix checkver script

- bucket/winbtrfs-np.json
As of 1.8.2, normal pnputil installation works now.
> winbtrfs-np: Fix installation, remove `nefcon` dependency

- bucket/nvidia-display-driver-dch-np.json
- bucket/nvidia-display-driver-np.json
Resolves #45 
I've been running these auto-update instructions in my scoop bucket for a bit. https://github.com/scowalt/scoop-apps/blob/main/bucket/geforce-game-ready-driver.json
I updated the path to reflect the `dl.7z` logic.
> Fix Nvidia display driver packages

- bucket/portmaster-np.json
The reason for this is because whenever the main portmaster repo publishes a release, the version number changes, but the hash does not. This is because that is the software being updated, not the package. The package version is 1.0.0, the software version is 1.0.7.
> portmaster-np: Change `checkver` to be more accurate

- bucket/pdf24-creator-np.json
Relates to #163
**EDIT:** Added `32bit` to `architecture` and `autoupdate`.
> pdf24-creator-np: Fixed `autoupdate` hash extraction to be more accurate

- bucket/nodejs-lts-np.json
After the latest changes to nodejs.org the checkver script no longer works. To no longer be dependent on the layout of the website this PR instead uses the JSON document at https://nodejs.org/dist/index.json to get the latest LTS version
> nodejs-lts-np: update checkver, update to latest version

- bucket/powertoys-np.json
As suggested in #321, revert back to lowercase and change tag extraction similar than the one for portable version.
Relates to #321 due to [powertoys@0.82.1: Fix for the tag change #13622](https://github.com/ScoopInstaller/Extras/pull/13622) with same tag extraction method than [powertoys: Update to version 0.82.1 #13612](https://github.com/ScoopInstaller/Extras/pull/13612)
> powertoys@0.82.1: Fix for the tag change

- bucket/pgadmin4-np.json
Refresh of installer arguments in order to:
* support silent installs in both user and global contexts => `SUPPRESSMSGBOXES` will let the installer assume local user install if it does not have admin rights instead of asking for elevated privileges
* get rid of a post_install error in case of local user install  (because 'pgAdmin 4' folder can't be located under the common start menu) by using `NOICONS` during install instead of  trying to remove start menu icons after the fact
> pgadmin4-np: Silent user install support

- bucket/file-converter-np.json
- Due to https://github.com/ScoopInstaller/Nonportable/pull/304#issuecomment-2092893210 also needs update to v2.1 and change to 64bit only
- The project github.com/Tichau/FileConverter links to file-converter.io and vice-versa.
Closes #303
(reopened to trigger GHA manifest validation)
> file-converter-np: Update to v2.1, 64bit only and fix wrong homepage URL

- bucket/office-365-apps-minimal-np.json
- bucket/office-365-apps-np.json
This PR fixes the download url , so it doesn't reports random values.
This in turn will fix the hash issues with the following packages:
* `office-365-apps-np`
* `office-365-apps-minimal-np`
This will also fix the rouge version check running every excavation event, resulting in at least 600 incorrect commits.
Relates to #419 #417 #412 #411 #407  #402 #396 #388 #386 #384 #383 #382 ... etc.
Closes: #423
> office-365-apps-np@*: fix version checker

- bucket/notepads-np.json
Get appx package name for `$package_name` one more time if it is null
Tested with debug function
```json
{
"post_install": [
"while ($null -eq $package_name) {",
"    Start-Sleep -Milliseconds 250",
"    $package_name = (Get-AppxPackage -Name '*JackieLiu*Notepads*').PackageFamilyName",
"}",
"debug $package_name",
"while (-not (Test-Path \"$env:LOCALAPPDATA\\Packages\\$package_name\\Settings\\settings.dat\")) { Start-Sleep -Milliseconds 250 }",
"Copy-Item -Recurse -Force \"$dir\\Settings\" -Destination \"$env:LOCALAPPDATA\\Packages\\$package_name\""
]
}
```
Output in installation
```plaintext
> gsudo scoop install notepads-np
WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
WARN  To disable this …
```
> notepads-np: Fix $package_name value error in post_install script

- bucket/virtualbox-with-extension-pack-np.json
Oracle changed the download path for the Extension Pack.  Updated autoupdate URL, then updated manifest using `checkver.ps1`.
Closes #356
> virtualbox-with-extension-pack-np@7.0.20:  fix autoupdate url

- bucket/pdf24-creator-np.json
Stopping the Windows explorer process isn't needed for installing and uninstalling.
> pdf24-creator-np: Update `post_install` and `pre_uninstall` script

- bucket/voicemeeter-banana-np.json
- bucket/voicemeeter-np.json
- bucket/voicemeeter-potato-np.json
Updates the following packages to the correct version when downloading from the source:
- `voicemeeter-np`
- `voicemeeter-banana-np`
- `voicemeeter-potato-np`
Relates to #328 
Relates to #329 
Relates to #330
> Update version of all 3 VoiceMeeter application packages

- bucket/vokoscreenng-np.json
Version 4.1.0 or later distributed with vcredist dll and no longer contains vcredist installer.  
This PR simply remove vcredist installer from removal targets in post_install script.
Affected since: 4.1.0 (and now 4.5.0)
Closes #298
> vokoscreenng-np: Exclude non-existent files from post_install deletion
