ScoopInstaller/Nonportable

.github/ISSUE_TEMPLATE/Package_request.md

fix(#7): Update ISSUE_TEMPLATE for Nonportable bucket

---

bucket/peace-np.json

peace-np: Add version 1.6.1.2

---

bucket/rom-properties-np.json

rom-properties-np: Add version 1.9

---

bucket/winbtrfs-np.json

winbtrfs-np: Do not run uninstaller on upgrade

---

bucket/dshidmini-np.json
bucket/winbtrfs-np.json

Virtual HID Mini-user-mode-driver for Sony DualShock 3 Controllers

dshidmini-np: Add version 2.2.282.0

---

bucket/dshidmini-np.json
bucket/equalizer-apo-np.json
bucket/fluent-terminal-np.json
bucket/icaros-np.json
bucket/lockhunter-np.json
bucket/peace-np.json
bucket/wireguard-np.json
bucket/xampp-np.json

Did a simple search and replace across all files

chore: Use break instead exit

---

bucket/teamviewer-np.json

teamviewer-np: add architecture field

---

bucket/teracopy-np.json

update to 3.8+ new msi installer parameter for slient install
Closes #XXXX
Relates to #XXXX

teracopy-np: Update to version 3.9, Modify installer

---

bucket/winbtrfs-np.json

Accidentally removed this, my bad

winbtrfs-np: Add `Out-Null` to Invoke-ExternalCommand

---

bucket/xysubfilter-libass-np.json
bucket/xysubfilter-np.json

An open-source DirectShow subtitle renderer. Moving the package from the Extras bucket
Also add libass variant

xysubfilter-np: Add version 3.1.0.752

---

bucket/notepads-np.json

notepads-np: Fix uninstall using gsudo

---

bucket/vmware-workstation-player-np.json

vmware-workstation-player-np: Add version 17.0.0-20800274

---

bucket/goodsync-np.json

Closes https://github.com/ScoopInstaller/Extras/issues/1661

goodsync-np: Add version 12.1.4

---

bucket/logitech-gaming-software-np.json

logitech-gaming-software-np: Add `checkver`, and `autoupdate`

---

bucket/powertoys-np.json

powertoys-np: Remove unneeded "depends" property

---

bucket/teamviewer-np.json

teamviewer-np: Update to version 15.35.9 and fix `checkver`

---

bucket/powertoys-np.json

Fixed silent install/uninstall.

powertoys-np: fix silent install/uninstall

---

bucket/encodegui-np.json

encodegui-np: add version 1.1.2

---

bucket/pdf24-creator-np.json

pdf24-creator-np: add version 11.10.0

---

bucket/burp-suite-community-np.json
bucket/burp-suite-pro-np.json

Relates to https://github.com/ScoopInstaller/Extras/issues/6910

burp-suite-np: Add version 2023.1

---

bucket/vokoscreenng-np.json

Closes https://github.com/ScoopInstaller/Extras/issues/8926

vokoscreenng-np: Add version 3.5.0

---

bucket/grammarly-np.json

Closes https://github.com/ScoopInstaller/Extras/issues/7126

grammarly-np: Add version 1.0.23.347

---

bucket/hp-support-assistant-np.json

hp-support-assistant-np: Add version 9.20.22.0.142501-143000.142943

---

bucket/files-np.json

Closes https://github.com/ScoopInstaller/Extras/issues/9279

files-np: Add version 2.4.21

---

bucket/translucenttb-np.json

Closes https://github.com/ScoopInstaller/Extras/issues/10071

translucenttb-np: Add version 2022.1

---

bucket/vmware-horizon-client-np.json

[VMware Horizon Client for Windows 2209 Release Notes](https://docs.vmware.com/en/VMware-Horizon-Client-for-Windows/2209/rn/vmware-horizon-client-for-windows-2209-release-notes/index.html#whatsnew)

vmware-horizon-client-np@2209-8.7.0-20649873: Update to latest version and fix checkver

---

bucket/spotx-np.json

- fixed repository url
- added parameter `new_theme` for new theme

spotx-np: fixed url and added new theme

---

bucket/scilab-np.json

Closes https://github.com/ScoopInstaller/Extras/issues/10248

scilab-np: Add version 6.1.1

---

bucket/open-shell-np.json

Relates to https://github.com/ScoopInstaller/Extras/issues/5100

open-shell-np: Add version 4.4.170

---

bucket/textpad8-np.json

textpad8-np: Add version 8.15.1

---

bucket/textpad-np.json

textpad-np: Add version 9.0.1

---

bucket/10x-np.json

Closes https://github.com/ScoopInstaller/Extras/issues/10317

10x-np: Add version 0.35.84

---

bucket/musicbee-np.json

musicbee-np: Add version 3.4.8033

---

bucket/freelan-np.json

Closes https://github.com/ScoopInstaller/Extras/issues/10319

freelan-np: Add version 2.2.0

---

bucket/musicbee-np.json

See https://github.com/ScoopInstaller/Extras/pull/10632/files#diff-5af5b9c744ac43d6d2b8911d637944b3801016ec805806c25030b2329ec247d0R34

musicbee-np: Update checkver

---

bucket/protonvpn-np.json

Updated the `URL`, `hash`, added `architecture`, updated the `pre_install` & `pre_uninstall` scripts, and updated `license`.

protonvpn-np: Updated the manifest.

---

bucket/powertoys-np.json

Update download url to the correct one and update hash in accordance to allow update to version 0.82.1.
Closes #320

powertoys-np@0.82.1: Fix download url

---

bucket/files-np.json

files-np: Update to version 3.7.11

---

bucket/auto-dark-mode-np.json

Update auto-dark-mode-np to latest version & add install different package by architecture
Relates to #410

auto-dark-mode-np update to latest

---

bucket/files-np.json

files-np: Update to version 3.9.1

---

bucket/protonvpn-np.json

Fixed the URLs for the latest version (3.5.1).
Relates to #370
Closes #369 and #375

protonvpn-np: Fixed urls

---

bucket/musicbee-np.json

add autoupdate, fix checkver and fix installer scripts
Closes #148

musicbee-np: Update to version 3.5.8447 & fix

---

bucket/zerotier-np.json

zerotier-np.json: update checkver regexp

---

bucket/mullvadvpn-np.json

Update mullvadvpn-np.json to 2024.2

---

bucket/glazewm-np.json

- Installs [GlazeWM v3.8.1](https://github.com/glzr-io/glazewm/releases/tag/v3.8.1) with capability for future updates utilizing .msi install on `arm64` and/or `x64` platforms.
- Properly creates and copies GlazeWM executables to directory `%ProgramFiles%\glzr.io\GlazeWM` for [UIAccess](https://learn.microsoft.com/en-us/previous-versions/windows/it-pro/windows-10/security/threat-protection/security-policy-settings/user-account-control-allow-uiaccess-applications-to-prompt-for-elevation-without-using-the-secure-desktop)
- UIAccess allows GlazeWM to run without elevation but to interact elevated programs for proper tiling. When running `glazewm.exe` in `%UserProfile%\scoop\apps` GlazeWM cannot run in [UIAccess](https://learn.microsoft.com/en-us/previous-versions/windows/it-pro/windows-10/sec …

glazewm-np: add to bucket v3.8.1

---

bucket/teamviewer-np.json

Closes #291
Seems file hash won't change for each download in current version so I revert some changes in https://github.com/ScoopInstaller/Nonportable/commit/44d8971a44afc590339c9919d053babac3bda7cc

teamviewer-np: Update URL, deprecate dummy file, ask for confirmation before stopping process

---

bucket/teamviewer-np.json

teamviewer-np: Remove residual content in installation script
